LaptopSystem.Web/Models/LaptopViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace LaptopSystem.Web.Models
{
    public class LaptopViewModel
    {
        public int Id { get; set; }
        public string Manufacturer { get; set; }
        public string Model { get; set; }
        public string ImageUrl { get; set; }
        public decimal Price { get; set; }
    }
}

LaptopSystem.Web/Controllers/LaptopsController.cs
using LaptopSystem.Models;
using LaptopSystem.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using System.Net.Http;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;

namespace LaptopSystem.Web.Controllers
{
    public class LaptopsController : BaseController
    {
        const int PageSize = 5;

        private IQueryable<LaptopViewModel> GetAllLaptops()
        {
            var data = this.Data.Laptops.All().Select(x => new LaptopViewModel
            {
                Id = x.Id,
                ImageUrl = x.ImageUrl,
                Manufacturer = x.Manufacturer.Name,
                Model = x.Model,
                Price = x.Price,
            }).OrderBy(x => x.Id);

            return data;
        }

        public ActionResult KendoList()
        {
            return View();
        }

        public JsonResult GetLaptops([DataSourceRequest] DataSourceRequest request)
        {
            return Json(this.GetAllLaptops().ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetLaptopModelData(string text)
        {
            var result = this.Data.Laptops
                .All()
                .Where(x => x.Model.ToLower().Contains(text.ToLower()))
                .Select(x => new
                {
                    Model = x.Model
                });

            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetLaptopManufacturerData()
        {
            var result = this.Data.Manufacturers
                .All()
                .Select(x => new
                {
                    ManufacturerName = x.Name 
                });

            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Search(SubmitSearchModel submitModel)
        {
            var result = this.Data.Laptops.All();

            if (!string.IsNullOrEmpty(submitModel.ModelSearch))
            {
                result = result.Where(x => x.Model.ToLower().Contains(submitModel.ModelSearch.ToLower()));
            }

            if (submitModel.ManufSearch != "All")
            {
                result = result.Where(x => x.Manufacturer.Name == submitModel.ManufSearch);
            }

            if (submitModel.PriceSearch != 0)
            {
                result = result.Where(x => x.Price < submitModel.PriceSearch);
            }

            var endResult = result.Select(x => new LaptopViewModel
            {
                Id = x.Id,
                Model = x.Model,
                Manufacturer = x.Manufacturer.Name,
                ImageUrl = x.ImageUrl,
                Price = x.Price
            });

            return View(endResult);
        }

        // Laptops/List/5
        [Authorize]
        public ActionResult List(int? id)
        {
            int pageNumber = id.GetValueOrDefault(1);

            var viewModel = GetAllLaptops().Skip((pageNumber - 1) * PageSize).Take(PageSize).ToList();
            ViewBag.Pages = Math.Ceiling((double)GetAllLaptops().Count() / PageSize);

            return View(viewModel);
        }

        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult PostComment(SubmitCommentModel commentModel)
        {
            if (ModelState.IsValid)
            {
                var username = this.User.Identity.GetUserName();
                var userId = this.User.Identity.GetUserId();

                this.Data.Comments.Add(new Comment()
                {
                    AuthorId = userId,
                    Content = commentModel.Comment,
                    LaptopId = commentModel.LaptopId, 
                });

                this.Data.SaveChanges();

                var viewModel = new CommentViewModel { AuthorUsername = username, Content = commentModel.Comment };
                return PartialView("_CommentPartial", viewModel);
            }

            return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest, ModelState.Values.First().ToString());
        }

        public ActionResult Details(int id)
        {
            var userId = User.Identity.GetUserId();

            var viewModel = this.Data.Laptops.All().Where(x => x.Id == id)
                .Select(x => new LaptopDetailsViewModel
                {
                    Id = x.Id,
                    AdditionalParts = x.AdditionalParts,
                    Comments = x.Comments.Select(y => new CommentViewModel { AuthorUsername = y.Author.UserName, Content = y.Content }),
                    Description = x.Description,
                    HardDiskSize = x.HardDiskSize,
                    ImageUrl = x.ImageUrl,
                    ManufacturerName = x.Manufacturer.Name,
                    Model = x.Model,
                    MonitorSize = x.MonitorSize,
                    Price = x.Price,
                    RamMemorySize = x.RamMemorySize,
                    Weight = x.Weight,
                    UserCanVote = !x.Votes.Any(pesho => pesho.VotedById == userId),
                    Votes = x.Votes.Count()
                }).FirstOrDefault();

            return View(viewModel);
        }

        public ActionResult Vote(int id)
        {
            var userId = User.Identity.GetUserId();

            var canVote = !this.Data.Votes.All().Any(x => x.LaptopId == id && x.VotedById == userId);

            if (canVote)
            {
                this.Data.Laptops.GetById(id).Votes.Add(new Vote
                {
                    LaptopId = id,
                    VotedById = userId
                });

                this.Data.SaveChanges();
            }

            var votes = this.Data.Laptops.GetById(id).Votes.Count();

            return Content(votes.ToString());
        }
    }
}

LaptopSystem.Web/Views/Laptops/Details.cshtml
@model LaptopSystem.Web.Models.LaptopDetailsViewModel
@{
    ViewBag.Title = "Details";
}

<h2>@Model.ManufacturerName @Model.Model</h2>
<div class="row">
    <div class="span4">
        <div><strong>Monitor:</strong> @Model.MonitorSize''</div>
        <div><strong>RAM:</strong> @Model.RamMemorySize GB</div>
        <div><strong>Price:</strong> $@Model.Price</div>
    </div>
    <div class="span4">
        <img src="@Model.ImageUrl" alt="@Model.ManufacturerName @Model.Model" />
    </div>
    <div class="span4">
        @if (Model.Weight.HasValue) { <div><strong>Weight:</strong> @Model.Weight Kg</div> }
        @if (!string.IsNullOrEmpty(Model.AdditionalParts)) { <div><strong>Additional parts:</strong> @Model.AdditionalParts</div> }
        @if (!string.IsNullOrEmpty(Model.Description)) { <div><strong>Description:</strong><br />@Model.Description</div> }
    </div>
</div>

<div>
    Votes: <span id="laptop-votes">@Model.Votes</span> 
    @if (User.Identity.IsAuthenticated && Model.UserCanVote)
    {
        @Ajax.ActionLink("Vote", "Vote", new { id = Model.Id }, new AjaxOptions { InsertionMode = InsertionMode.Replace, UpdateTargetId = "laptop-votes", HttpMethod = "Post", OnSuccess = "hideVoteButton" }, new { id="vote-button", @class = "btn" })
    }
</div>
<br />
<div id="Comments">
    @foreach (var comment in Model.Comments)
    {
        @Html.Partial("_CommentPartial", comment)
    }
</div>
@if (User.Identity.IsAuthenticated)
{
    using(Ajax.BeginForm("PostComment", new AjaxOptions { HttpMethod = "Post", InsertionMode = InsertionMode.InsertAfter, UpdateTargetId = "Comments", OnFailure="commentPostFailure" }))
    {
        @Html.Hidden("LaptopId", Model.Id)
        @Html.TextArea("comment")
        @Html.AntiForgeryToken()
        <input type="submit" value="Submit comment" />
    }
}

@section scripts{
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script>
        function commentPostFailure() {
            alert("Error");
        }

        function hideVoteButton() {
            $("#vote-button").hide();
        }
    </script>
}

LaptopSystem.Web/Views/Laptops/KendoList.cshtml
@{
    ViewBag.Title = "KendoList";
}

<h2>KendoList</h2>

<div class="row-fluid">
    @using (Html.BeginForm("Search", "Laptops", FormMethod.Post))
    {
        <div>
            Search by model
        </div>
        @(Html.Kendo()
            .AutoComplete()
            .Name("modelsearch")
            .DataTextField("Model")
            .MinLength(3)
            .Placeholder("Enter model")
            .DataSource(data =>
            {
                data.Read(read =>
                    {
                        read.Action("GetLaptopModelData", "Laptops")
                            .Data("onAdditionalData");
                    })
                    .ServerFiltering(true);
            }))
        <br />
        <div>
            Search by manufacturer
        </div>
        @(Html.Kendo()
        .DropDownList()
        .Name("manufsearch")
        .DataTextField("ManufacturerName")
        .DataValueField("ManufacturerName")
        .OptionLabel("All")
        .DataSource(data =>
        {
            data.Read(read => read.Action("GetLaptopManufacturerData", "Laptops"));
            data.ServerFiltering(true);
        }))
        <br />
        <div>
            Search by price
        </div>
        @(Html.Kendo()
        .NumericTextBox()
        .Name("pricesearch")
        .Min(600)
        .Max(3000))
        
        <div>
            <input type="submit" value="Search" class="btn"/>
        </div>
        
    }
</div>
<br />

@(Html.Kendo()
    .ListView<LaptopSystem.Web.Models.LaptopViewModel>()
    .Name("laptops")
    .TagName("div")
    .ClientTemplateId("laptop-template")
    .Pageable()
    .DataSource(data =>
    {
        data.Read("GetLaptops", "Laptops");
        data.ServerOperation(true);
        data.PageSize(5);
    }))

<script id="laptop-template" type="text/x-kendo-template">
    <div class="row-fluid">
        <div class="span4">
            <img src="#: ImageUrl #" />
        </div>
        <div class="span4">
            <h3>#: Manufacturer # #: Model #</h3>
        </div>
        <div class="span4">
            <p><a href="/Laptops/Details/#: Id #" class="btn">Price: #: Price #</a></p>
        </div>
    </div>
</script>

<script>
    function onAdditionalData() {
        return {
            text: $('#modelsearch').val()
        };
    }
</script>

LaptopSystem.Web/Views/Laptops/List.cshtml
@model IEnumerable<LaptopSystem.Web.Models.LaptopViewModel>
@{
    ViewBag.Title = "Laptops";
}

<h2>@ViewBag.Title</h2>

@foreach (var laptop in Model)
{
    <div class="row">
        <div class="span4">
            <img src="@laptop.ImageUrl" />
        </div>
        <div class="span4">
            @laptop.Manufacturer @laptop.Model
        </div>
        <div class="span4">
            <p><a class="btn" href="@Url.Action("Details", "Laptops", new { laptop.Id })">Price @laptop.Price</a></p>
        </div>
    </div>
}

@for (int i = 1; i <= ViewBag.Pages; i++)
{
    <a href="@Url.Action("List", new { id = i })">@i</a>
}

LaptopSystem.Web/Views/Laptops/Search.cshtml
@model IEnumerable<LaptopSystem.Web.Models.LaptopViewModel>

@{
    ViewBag.Title = "Search result";
}

<h2>@ViewBag.Title</h2>

<div class="row-fluid">
@for (int i = 0; i < Model.Count(); i++)
{
    var laptop = Model.ElementAt(i);
    <div class="span4">
        <h2>@laptop.Manufacturer @laptop.Model</h2>
        <img src="@laptop.ImageUrl" />
        <p><a class="btn" href="@Url.Action("Details", "Laptops", new { laptop.Id })">Price @laptop.Price</a></p>
    </div>

    if (i > 0 && (i + 1) % 3 == 0)
    {
        @:</div>
        @:<div class="row-fluid">
        }
}
</div>